---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- News:
    - Patriots:
        href: https://patriots.win/
        description: Patriots.win
    - Instapundit:
        href: https://pjmedia.com/instapundit/
        description: Instapundit
    - Breibart:
        href: https://breitbart.com/
        description: Breibart

- Home Automation:
    - Home Assistant:
        icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/home-assistant.png
        href: http://homeassistant.local:8123/
        description: Home Assistant
    - Ubiquity:
        icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/ubiquiti-unifi.png
        href: https://unifi.ui.com/
        description: Ubiquity

- Shop:
    - 3d Printers:
        href: https://connect.prusa3d.com/printers/table?sortBy=state%2Cname
        description: 3d Printers
    - Printables:
        href: https://www.printables.com/
        description: Printables
    - Thingiverse:
        href: https://www.thingiverse.com/
        description: Thingiverse
    - Gridfinity:
        - Gridfinity:
            href: https://gridfinity.perplexinglabs.com/
            description: Gridfinity
        - Gridfinity Labels:
            href: https://gridfinitylabels.com/
            description: Gridfinity Labels

- AI:
    - Grok:
        href: https://grok.com/
        description: Grok Chat
